version: '3.9'
services:
  web:
    image: 'gitlab/gitlab-ce:15.3.3-ce.0'
    restart: always
    hostname: 'DOMAIN.COM'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://DOMAIN.COM'
        postgresql['enable'] = false
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'unicode'
        gitlab_rails['db_host'] = '192.168.10.153'
        gitlab_rails['db_database'] = 'gitlab'
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['db_password'] = '@Mk4TfbUs__2bngZ'
        gitlab_rails['time_zone'] = 'UTC'
        gitlab_rails['db_port'] = '5432'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
